jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'

aws:
  # user: root
  #accessKeyId: AKIAW3MECWUYFRDFO5GI
  #secretKey: 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

  # user: kudondza-user-production
  accessKeyId: AKIAW3MECWUYMZWWMU4J
  secretKey: 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

  region.static: us-east-1

server:
  port: 8080

spring:

  profiles:
    active: prod

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false