
server:
  port: 8080

aws:
  accessKeyId: AKIAW3MECWUYLS6ENYCX
  secretKey: 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
  region.static: us-east-1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Africa/Harare
    username: root
    password: root

  # Mysql 8.0
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false