jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'

aws:
  # user: root
  #accessKeyId: AKIAW3MECWUYACIYYZ2P
  #secretKey: 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

  # user: kudondza-user-production
  accessKeyId: AKIAU6GDVYYOJOHKDO7G
  secretKey: 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

  region.static: eu-north-1

mpesa:
  api:
    api-key: 3ioydbucapwpkio6ce4uw8oikoslogwr
    public-key: MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAmptSWqV7cGUUJJhUBxsMLonux24u+FoTlrb+4Kgc6092JIszmI1QUoMohaDDXSVueXx6IXwYGsjjWY32HGXj1iQhkALXfObJ4DqXn5h6E8y5/xQYNAyd5bpN5Z8r892B6toGzZQVB7qtebH4apDjmvTi5FGZVjVYxalyyQkj4uQbbRQjgCkubSi45Xl4CGtLqZztsKssWz3mcKncgTnq3DHGYYEYiKq0xIj100LGbnvNz20Sgqmw/cH+Bua4GJsWYLEqf/h/yiMgiBbxFxsnwZl0im5vXDlwKPw+QnO2fscDhxZFAwV06bgG0oEoWm9FnjMsfvwm0rUNYFlZ+TOtCEhmhtFp+Tsx9jPCuOd5h2emGdSKD8A6jtwhNa7oQ8RtLEEqwAn44orENa1ibOkxMiiiFpmmJkwgZPOG/zMCjXIrrhDWTDUOZaPx/lEQoInJoE2i43VN/HTGCCw8dKQAwg0jsEXau5ixD0GUothqvuX3B9taoeoFAIvUPEq35YulprMM7ThdKodSHvhnwKG82dCsodRwY428kg2xM/UjiTENog4B6zzZfPhMxFlOSFX4MnrqkAS+8Jamhy1GgoHkEMrsT5+/ofjCx0HjKbT5NuA2V/lmzgJLl3jIERadLzuTYnKGWxVJcGLkWXlEPYLbiaKzbJb2sYxt+Kt5OxQqC1MCAwEAAQ==
    base-url: api.sandbox.vm.co.mz
    port: 18352
    c2b-path: /ipg/v1x/c2bPayment/singleStage/
    initiator: 171717

emola:
  url: https://XXX.XXX.XXX.XXX:YYYY/BCCSGateway/BCCSGateway
  username: SEU_USERNAME
  password: SEU_PASSWORD
  partnerCode: SEU_PARTNER_CODE
  key: SUA_PRIVATE_KEY

openai:
  api-key: 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
  url: https://api.openai.com/v1/completions

server:
  address: 0.0.0.0
  port: 8080

  tomcat:
    max-swallow-size: 100MB        # Tomcat: tamanho máximo para upload
    max-http-form-post-size: 100MB # Tomcat: tamanho máximo POST

spring:

  profiles:
    #active: stage
    active: dev

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  #security:
  #  oauth2:
  #    client:
  #      registration:
  #        google:
  #          client-id: SEU_CLIENT_ID
  #          client-secret: SEU_CLIENT_SECRET
  #          scope: profile, email

  #redis:
  #  host: localhost
  #  port: 6379
  #  password:
  #  timeout: 2000