jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'

aws:
  accessKeyId: AKIAW3MECWUYLS6ENYCX
  secretKey: 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
  region.static: us-east-1

server:
  port: 8080

spring:

  profiles:
    active: dev

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false