package com.fabiocondo.enumeration;

public enum NotificationType {
    COMPETITION_STARTED,
    COMPETITION_FINISHED,
    COMPETITION_INVITE,
    PARTICIPATION_REQUEST,
    FRIEND_REQUEST,
    FRIEND_ACCEPTED,
    POST_LIKE,
    COMMENT_LIKE,
    COMMENT_REPLY,
    POST_COMMENT,
    MENTION,
    GROUP_INVITE,
    MESSAGE_RECEIVED
}

